/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bussystem.gui;
import bookdetails.util.BookPojo;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
public class Detail extends javax.swing.JFrame {
    private String name;
    private String email1;
    private String busname;
    private String email;
     private String senderId,pwd,recId;
    private String msg;
    private Session session;
    public Detail(){}
    public Detail(TicketPojo tic,BookPojo obj,String email) {
        initComponents();
        this.email=email;
        email1=tic.getEmail1();
        this.setVisible(true);
        this.dispose();
        String str=null;
        str="Name-"+tic.getName()+"\n"+"Email-"+tic.getEmail()+"\n"+"BusName-"+obj.getBusname()+"\n"+obj.getSource()+"\t"+obj.getDestination()+"\n"+(Double.parseDouble(obj.getPrice())*tic.getSeat());
        msg=str;
        detail1btn.setText(str);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailbtn = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        detail1btn = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        homebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        detail1btn.setColumns(20);
        detail1btn.setRows(5);
        jScrollPane1.setViewportView(detail1btn);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ticket Details:-");

        homebtn.setText("HomePage");
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout detailbtnLayout = new javax.swing.GroupLayout(detailbtn);
        detailbtn.setLayout(detailbtnLayout);
        detailbtnLayout.setHorizontalGroup(
            detailbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailbtnLayout.createSequentialGroup()
                .addGroup(detailbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailbtnLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailbtnLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(homebtn)
                .addGap(63, 63, 63))
        );
        detailbtnLayout.setVerticalGroup(
            detailbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailbtnLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homebtn)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        detailbtn.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        detailbtn.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        detailbtn.setLayer(homebtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailbtn)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailbtn)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setMailParameters()
    {
        senderId="saurabhgrade2010@gmail.com";
        pwd="Sgrajput12@";   
        Properties props = new Properties();  
        props.put("mail.smtp.host", "smtp.gmail.com");  
        props.put("mail.smtp.socketFactory.port", "465");  
        props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");  
        props.put("mail.smtp.auth", "true");  
        props.put("mail.smtp.port", "465");  
   
        session = Session.getDefaultInstance(props,  
        new javax.mail.Authenticator() {  
        protected PasswordAuthentication getPasswordAuthentication() {  
        return new PasswordAuthentication(senderId,pwd);//change accordingly  
        }  
        }); 
    }
    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
         // TODO add your handling code here:
        setMailParameters();
        try {  
                MimeMessage message = new MimeMessage(session);  
                message.setFrom(new InternetAddress(senderId));//change accordingly  
               // message.addRecipient(Message.RecipientType.TO,new InternetAddress(recId));  
                message.addRecipients(Message.RecipientType.TO, email1);
                message.setSubject("Ticket Succussfull @ Saurabh App");
                msg="Thank for joining with us\nYour Ticket Details : "+msg;
                message.setText(msg);  
     
                //send message  
                Transport.send(message);  
  
                //JOptionPane.showMessageDialog(null,"Password Mail Sent Successfully!","Success!",JOptionPane.INFORMATION_MESSAGE); 
        } 
        catch(MessagingException e) {
            JOptionPane.showMessageDialog(null,"Error!:"+e,"Sorry!",JOptionPane.ERROR_MESSAGE);
            throw new RuntimeException(e);
        }  
        new CustomerHomepage(email).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea detail1btn;
    private javax.swing.JDesktopPane detailbtn;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
